github: # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
patreon: IvanStoychev
ko_fi: IvanStoychev
custom: ["https://www.paypal.com/paypalme/IvanStoychevProjects", "https://www.buymeacoffee.com/IvanStoychev"]